### ISSUE TITLE
Not work links on callistosecurity.com

### ISSUE THREAD

**Issue by 11FaTuSh11** [CallistoSecurity/Smart-contract-auditing#1]
callistosecurity.com
None of the links on your website work! also no automatic redirect to **https**
Then why is there a website at all?
![image](https://user-images.githubusercontent.com/73724555/230468464-bf591ad9-aea0-479a-b426-151fda997696.png)
Fix it please.

WordPress plugin error keeps popping up 
![image](https://user-images.githubusercontent.com/73724555/230468148-93c8605e-1824-4e2e-8b49-472a0cad9398.png)

```
Fatal error: Uncaught Error: Cannot use object of type WpOrg\Requests\Response as array in /web/htdocs6/callistosecuritycom/home/www/wp-content/plugins/cleantalk-spam-protect/lib/Cleantalk/Common/HTTP/Response.php:24 Stack trace: #0 /web/htdocs6/callistosecuritycom/home/www/wp-content/plugins/cleantalk-spam-protect/lib/Cleantalk/ApbctWP/HTTP/Request.php(57): Cleantalk\Common\HTTP\Response->__construct(Object(WpOrg\Requests\Response), Array) #1 /web/htdocs6/callistosecuritycom/home/www/wp-content/plugins/cleantalk-spam-protect/lib/Cleantalk/ApbctWP/HTTP/Request.php(22): Cleantalk\ApbctWP\HTTP\Request->requestSingle() #2 /web/htdocs6/callistosecuritycom/home/www/wp-content/plugins/cleantalk-spam-protect/lib/Cleantalk/ApbctWP/Helper.php(57): Cleantalk\ApbctWP\HTTP\Request->request() #3 /web/htdocs6/callistosecuritycom/home/www/wp-content/plugins/cleantalk-spam-protect/lib/Cleantalk/ApbctWP/Helper.php(163): Cleantalk\ApbctWP\Helper::httpRequest('http://www.call...', Array, Array) #4 /web/htdocs6/callistosecuritycom/home/www/w in /web/htdocs6/callistosecuritycom/home/www/wp-content/plugins/cleantalk-spam-protect/lib/Cleantalk/Common/HTTP/Response.php on line 24
There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)
```

**Comment by 11FaTuSh11** [comment]
@Dexaran check pls
